### ISSUE TITLE
suggestion to fork, as a security precaution?

### ISSUE THREAD

**Issue by PatNeedham** [thii/aws-codebuild-extras#12]
Excellent library, thank you for making the Github branch name available inside CodeBuild! As was noted on [a StackOverflow answer](https://stackoverflow.com/a/50379791/772985), it's potentially dangerous to run `curl` to obtain the install script in this repo, due to the non-zero chances of an account breach. What do you think about giving mention to that concern in the README, along with a suggestion to fork the repo, so that folks who still want this solution can do so by accessing it from their own repos?

**Comment by thii** [comment]
Ah yeah. You can also lock the curl command to a known commit. I’ll update the README.
