### ISSUE TITLE
Any chance to get working with CodePipeline?

### ISSUE THREAD

**Issue by oscaraparicio77** [thii/aws-codebuild-extras#9]
The variables are empty when i use the .sh file.

I obtain this error:

fatal: not a git repository (or any parent up to mount point /codebuild) 
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set). 

Thanks for this project

**Comment by oscaraparicio77** [comment]
The problem is Codepipeline at the moment to create source artifact for Codebuild, don't save .git directory, adding a git clone to builspec.yml your script works, nice work!!

**Comment by bilics** [comment]
Hi! @oscaraparicio77 

I am having the same problem - what exactly did you add to the buildspec.yml ?

Thanks!
